name: Bug report
description: Report a reproducible defect.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Describe the bug and impact.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact commands, inputs, and expected vs actual behavior.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, runtime versions, and app area.
      placeholder: Windows 11, Python 3.13, Node 22, backend/frontend/web/docs
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant error output or screenshots.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I searched for existing issues first.
          required: true
